liip_imagine:
    driver: gd

    resolvers:
        flysystem_resolver:
            flysystem:
                filesystem_service: oneup_flysystem.uploads_article_filesystem
                root_url: "%article_uploads_url%"
                cache_prefix: media/cache
                visibility: public

    cache: flysystem_resolver

    twig:
        mode: lazy
    loaders:
        articles_flysystem_loader:
            flysystem:
                filesystem_service: oneup_flysystem.uploads_article_filesystem
    data_loader: articles_flysystem_loader

    filter_sets:
        cache: ~

        picture_preview:
            quality: 75
            filters:
                thumbnail: { size: [ 100, 100 ], mode: inset }

        article_preview:
            quality: 60
            filters:
                thumbnail: { size: [ 200, 200 ], mode: outbound }

        article_show_edit:
            quality: 60
            filters:
                thumbnail: { size: [ 300, 300 ], mode: inset }

        pict_in_article_preview:
            quality: 60
            filters:
                thumbnail: { size: [ 100, 100 ], mode: outbound }

        view_article:
            quality: 60
            filters:
                thumbnail: { size: [ 800, 600 ], mode: outbond }