# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle
oneup_flysystem:
    adapters:
        uploads_article_adapter:
            local:
                location: '%kernel.project_dir%/public/%article_uploads%'
    filesystems:
        uploads_article:
            adapter: uploads_article_adapter
